version: '{build}'
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet restore geometry3Sharp_netstandard.csproj

    dotnet build geometry3Sharp_netstandard.csproj -c Release

    dotnet pack geometry3Sharp_netstandard.csproj -c Release
test: off
artifacts:
- path: bin\Release\*.nupkg
deploy: off