version: '{build}'
image: Visual Studio 2017
build_script:
- cmd: >-
    dotnet restore geometry3Sharp_netstandard.csproj

    dotnet build geometry3Sharp_netstandard.csproj -c Release

    dotnet pack geometry3Sharp_netstandard.csproj -c Release
test: off
artifacts:
- path: bin\Release\*.nupkg
deploy:
  provider: NuGet
#  server:                  # remove to push to NuGet.org
  api_key:
    secure: NwCvdkjy/Jpu+Cev4PeXnCdyEtf5F5O4bDtBoXisEKkez6R+U5Wk12hdHNa1NTFT
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/